### ISSUE TITLE
Git file lock exists

### ISSUE THREAD

**Issue by LucasVerneyDGE** [ambanum/CGUs#37]
Hi,

When starting with an empty `cgus-data` git repository and running `yarn start`, I get

```
[Fri Jul 03 2020 12:05:40] [ERROR]  [Discord-Terms of service] Error: Error: Could not commit undefined for undefined (raw version) due to error: Error: fatal: Unable to create '/home/lverney/cgus/cgus-data/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

    at file:///home/lverney/cgus/src/history/persistor.js:9:10
    at /home/lverney/cgus/node_modules/async/dist/async.js:1249:46
    at Array.forEach (<anonymous>)
    at trigger (/home/lverney/cgus/node_modules/async/dist/async.js:1249:27)
    at /home/lverney/cgus/node_modules/async/dist/async.js:1314:25
    at /home/lverney/cgus/node_modules/async/dist/async.js:321:20
    at invokeCallback (/home/lverney/cgus/node_modules/async/dist/async.js:179:13)
    at /home/lverney/cgus/node_modules/async/dist/async.js:173:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I did not yet dig much into this issue, sounds like a concurrent access to git repository in async promises.

Best,

**Comment by MattiSG** [comment]
Thanks a lot for reporting @LucasVerneyDGE! 🐞🙂 

Do you reproduce with the latest version, with the database being set up with `yarn run setup`?

**Comment by MattiSG** [comment]
If so, could you please provide us with `yarn --version` and `node --version`? 🙂

**Comment by LucasVerneyDGE** [comment]
Indeed, I cannot reproduce with latest version. Thanks for the fix!
